apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartfullstack.fullname" . }}-react-app-service
  labels:
  {{- include "chartfullstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.reactAppService.type }}
  selector:
    app: react-app
  {{- include "chartfullstack.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.reactAppService.ports | toYaml | nindent 2 }}