apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartfullstack.fullname" . }}-spring-boot-app-service
  labels:
  {{- include "chartfullstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.springBootAppService.type }}
  selector:
    app: spring-boot-app
  {{- include "chartfullstack.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.springBootAppService.ports | toYaml | nindent 2 }}