stages:
  - build
  - deploy
  
Build frontend:
  stage: build
  tags:
    - WSL
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"amF3aGVyYmVsbWFicm91azp6KzFpdGF2P1Zvc1dvMnJ1NjFlag==\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context frontend
      --dockerfile frontend/Dockerfile
      --destination jawherbelmabrouk/fullstack-demo:book-app-react-app
  when: manual

Build backend:
  stage: build
  needs:
    - Build frontend
  tags:
    - WSL
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"amF3aGVyYmVsbWFicm91azp6KzFpdGF2P1Zvc1dvMnJ1NjFlag==\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context backend
      --dockerfile backend/Dockerfile
      --destination jawherbelmabrouk/fullstack-demo:book-app-spring-boot-app
  when: manual

Deploy to Kubernetes:
  stage: deploy
  variables:
    KUBE_CONTEXT: fullstack-demo:wsl
  before_script:
    - if [ -n "$KUBE_CONTEXT" ]; then kubectl config use-context "$KUBE_CONTEXT"; fi
  tags:
    - WSL
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install fullstack-demo chartfullstack
  when: manual