---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: jawherbelmabrouk/fullstack-demo:book-app-spring-boot-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://pg-1c9cb8a8-postgresql-test-345346.i.aivencloud.com:16638/defaultdb?ssl=verify&user=avnadmin&password=AVNS_kI61k6Ekh_t1tLru2fp"
            - name: SPRING_DATASOURCE_USERNAME
              value: "avnadmin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "AVNS_kI61k6Ekh_t1tLru2fp"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: jawherbelmabrouk/fullstack-demo:book-app-react-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: NodePort

